apiVersion: v1
kind: Service
metadata:
  name: gotify-svc
  namespace: gotify
spec:
  selector:
    app: gotify-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
