apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: signoz-otel-ingressroute
  namespace: signoz
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`otel.local.net`) && PathPrefix(`/v1/metrics`)
      services:
        - name: signoz-helm-release-otel-collector.signoz
          port: 4318
    - kind: Rule
      match: Host(`otel.local.net`) && PathPrefix(`/v1/logs`)
      services:
        - name: signoz-helm-release-otel-collector.signoz
          port: 4318
    - kind: Rule
      match: Host(`otel.local.net`) && PathPrefix(`/v1/traces`)
      services:
        - name: signoz-helm-release-otel-collector.signoz
          port: 4318
