apiVersion: v1
kind: Service
metadata:
  name: clickhouse-svc
  namespace: clickhouse
spec:
  selector:
    app: clickhouse-deploy
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-zookeeper-svc
  namespace: clickhouse
spec:
  selector:
    app: clickhouse-zookeeper
  type:
  ports:
    - protocol: TCP
      port: 9181
      targetPort: 9181
